abandon_thresholds:
  min_recovery_odds: 0.4
  min_safu_score: 0.4
  min_score: 0.2
baseOrderUsdt: null
base_order_usdt: 200
btc_indicators:
  adx_max: 15
  macd_histogram_max: 0
  rsi_max: 40
buffer_zone_pct: 0
confidence: 0.7
confidence_dca_guard:
  confidence_score_min: 0.7
  macd_lift_min: 5.0e-05
  min_confidence_delta: 0.05
  min_tp1_shift_gain_pct: 1.1
  rsi_slope_min: 1
  safu_score_min: 0.5
currentScore: null
current_score: 0.65
drawdownPct: null
drawdown_pct: -8
drawdown_trigger_pct: 0.9
enforce_if: both
entryScore: null
entry_score: 0.75
health_scoring:
  decay_threshold: 0.3
  enabled: false
  health_thresholds:
    healthy: 0.7
    weak: 0.4
  indicator_thresholds:
    adx_min: 20
    macd_histogram_min: 0
    rsi_min: 45
  weights:
    confidence_score: 0.3
    entry_score_decay: 0.1
    indicator_health: 0.1
    recovery_odds: 0.4
    safu_score: 0.1
indicator_thresholds:
  adx: 10
  macd_histogram: 0
  rsi: 45
log_verbose: true
maxTradeUsdt: 1
max_tp1_shift_pct: 40
max_trade_usdt: 2000
min_be_improvement_pct: 0.8
min_confidence_odds: 0.85
min_recovery_probability: 0.85
ml_exit_threshold: 0.6
require_indicator_health: true
require_recovery_odds: true
require_tp1_feasibility: true
safuScore: null
safu_score: 0.8
safu_score_threshold: 0.5
score_decay_min: 0.2
so_volume_table:
- 20
- 10
- 19
- 36.1
- 68.59
- 130.32
- 247.61
- 470.46
- 893.87
soft_confidence_override:
  min_confidence: 0.75
  min_confidence_delta: 0.05
  min_drawdown_pct: 2
  min_health_score: 0.6
  min_recovery_odds: 0.8
  min_safu_score: 0.7
  min_tp1_shift_pct: 2
spend_adjustment_rules:
  low_dd_pct_limit: 1
  max_multiplier: 3
  min_volume: 20
  tp1_shift_soft_cap: 2.5
step_progress_guard:
  enabled: true
  min_be_improvement_pct: 1
  min_price_change_pct: 0.5
  min_seconds_elapsed: 900
step_repeat_guard:
  enabled: true
  min_conf_delta: 0.05
  min_tp1_delta: 1.2
tp1ShiftPct: null
tp1_shift_pct: 5
tp1_targets:
- 0.4
- 1.1
- 1.7
- 2.4
- 3
- 3.9
- 5.2
- 7.1
- 10
trajectory_thresholds:
  macd_lift_min: 0.0001
  rsi_slope_min: 1.5
use_btc_filter: false
use_confidence_override: false
use_ml_spend_model: true
use_safu_exit_model: true
use_soft_confidence_override: false
use_trajectory_check: true
zombie_tag:
  enabled: true
  max_drawdown_pct: 5
  max_macd_lift: 0
  max_rsi_slope: 0
  max_score: 0.3
  min_drawdown_pct: 0.5
  require_zero_recovery_odds: true
