min_score: 0.4
telegram_alerts: false
auto_close: false
weights:
  btc_rsi_below_30: 0.15
  btc_price_below_ema: 0.1
  btc_adx_above_30: 0.1
  token_price_below_vwap: 0.15
  token_macd_bearish: 0.1
  token_rsi_below_35: 0.1
  token_volume_drop: 0.15
  drawdown_gt_6: 0.05
  drawdown_gt_7: 0.1
safu_reentry:
  enabled: true
  require_btc_status: not_bearish
  cooldown_minutes: 30
  min_macd_lift: 5.0e-05
  min_rsi_slope: 1
  min_safu_score: 0.4
  allow_if_tp1_shift_under_pct: 30
