# strategies/confidence_safeguard.yaml

name: "Confidence Safeguard"
description: "Only fire DCA if confidence and SAFU align. Block when score is decaying or trajectory is flat."

indicators:
  rsi_min: 45
  macd_histogram_min: 0.0001
  adx_min: 12

trajectory:
  use: true
  macd_lift_min: 0.00005
  rsi_slope_min: 1.0

safu:
  min_score: 0.6

ml_rules:
  use_confidence: true
  min_confidence_score: 0.7
  min_confidence_delta: 0.05
  require_recovery_odds: true
  min_recovery_odds: 0.5

tp1:
  require_feasibility: true
  max_shift_pct: 2.0

zombie_protection: true
