# Trading mode
enabled: true
exchange: binance_futures
margin_mode: isolated            # isolated | cross
hedged_mode: true                # allow simultaneous long & short
max_leverage: 5
default_symbol_leverage: 5
liquidation_buffer_pct: 6.0      # block adds if liq is within this % of price

# Directions
allow_long: true
allow_short: true

# Entry source
entry_source:
  mode: manual                   # manual | fork
  tv_enabled: false              # only used if mode: fork
  backfill_days: 0               # fork mode only; 0 = today

# Manual symbols list (used when entry_source.mode=manual)
symbols:
  - BTCUSDT
  - ETHUSDT

# Short entry tuning (mirrors long but inverted)
short_entry:
  use_fork_inversion: true       # when mode: fork, invert gates for shorts
  rsi_max: 70                    # was 58 → loosened for testing
  macd_hist_max: 0.0000          # was -0.0001 → loosened for testing
  ema_trend: below_emas

# Sizing & risk
max_trade_notional: 10000        # per-position notional cap
max_account_notional: 50000      # total across all symbols
base_order_usdt: 200             # initial margin to post (guideline)
so_notional_table:               # DCA steps in NOTIONAL terms (USD)
  - 1000
  - 1500
  - 2500
  - 4000

# DCA gates (reuse your spot logic ideas)
drawdown_trigger_pct: 1.2
require_indicator_health: true
indicator_thresholds:
  rsi_min: 35                    # was 42 → loosened for testing
  macd_hist_min: -0.0002         # was 0.0001 → loosened for testing
  adx_min: 10                     # was 12 → loosened for testing

# Trajectory / odds (reuse existing ML)
use_trajectory_check: false      # was true → disabled for testing
trajectory_thresholds:
  macd_lift_min: 1.0e-04
  rsi_slope_min: 1.0
require_recovery_odds: true
min_recovery_probability: 0.5

# Tv / Fork Tie-in
fork_file: /home/signal/market7/output/final_fork_rrr_trades.json
tv_file: /home/signal/market7/output/fork_tv_adjusted.jsonl
fork_gate: true         # default true (can disable with --no-fork-gate)
tv_gate: true           # default true (can disable with --no-tv-gate)
fork_min_long: 0.60     # require >= for longs
fork_max_short: 0.40    # require <= for shorts
tv_bull: ["buy"]
tv_bear: ["sell"]

# Operations
dry_run: true                    # start in dry-run; flip to false when ready
log_verbose: true
