version: '3.8'

services:
  # Redis for caching and queues
  redis:
    image: redis:7-alpine
    container_name: marketpilot-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL for persistent data
  postgres:
    image: postgres:15-alpine
    container_name: marketpilot-postgres
    environment:
      POSTGRES_DB: marketpilot
      POSTGRES_USER: marketpilot
      POSTGRES_PASSWORD: marketpilot_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marketpilot"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Main trading application
  trading-app:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.minimal
    container_name: marketpilot-trading
    environment:
      - ENVIRONMENT=production
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - LOG_LEVEL=INFO
    volumes:
      - ../logs:/app/logs
      - ../data:/app/data
      - ../models:/app/models
      - ../config:/app/config
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "health_check.py"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
  postgres_data:

networks:
  default:
    name: marketpilot-network
