max_trade_usdt: 2000
base_order_usdt: 200
drawdown_trigger_pct: 1.2  # 🔧 Was 0.9, now slightly less sensitive
safu_score_threshold: 0.5
score_decay_min: 0.2
buffer_zone_pct: 0
require_indicator_health: true
indicator_thresholds:
  rsi: 42
  macd_histogram: 0.0001  # 🔧 More permissive for valid momentum
  adx: 12
use_btc_filter: false
btc_indicators:
  rsi_max: 35
  macd_histogram_max: 0
  adx_max: 15
use_trajectory_check: true
trajectory_thresholds:
  macd_lift_min: 1.0e-04
  rsi_slope_min: 1.0
require_tp1_feasibility: true
max_tp1_shift_pct: 25  # 🔧 Tighter limit on TP1 shift feasibility
require_recovery_odds: true
min_recovery_probability: 0.5
min_confidence_odds: 0.65
use_confidence_override: true
confidence_dca_guard:
  safu_score_min: 0.5
  macd_lift_min: 5.0e-05
  rsi_slope_min: 1
  confidence_score_min: 0.75
  min_confidence_delta: 0.1
  min_tp1_shift_gain_pct: 1.5
soft_confidence_override:
  enabled: false
min_be_improvement_pct: 2
step_repeat_guard:
  enabled: true
  min_conf_delta: 0.1
  min_tp1_delta: 1.5
  min_price_delta_pct: 0.5
so_volume_table:
- 20
- 15
- 25
- 40
- 65
- 90
- 150
- 250
- 400
spend_guard:
  enabled: true
  drawdown_thresholds:
    - { dd_pct: 0,  max_spend_usdt: 25 }
    - { dd_pct: 3,  max_spend_usdt: 35 }    # 🔧 Modified spend limit
    - { dd_pct: 5,  max_spend_usdt: 60 }    # 🔧 Modified spend limit
    - { dd_pct: 10, max_spend_usdt: 300 }
    - { dd_pct: 15, max_spend_usdt: 600 }
    - { dd_pct: 20, max_spend_usdt: 1000 }
    - { dd_pct: 30, max_spend_usdt: 1500 }
    - { dd_pct: 40, max_spend_usdt: 2000 }
tp1_targets:
- 0.4
- 1.1
- 1.7
- 2.4
- 3
- 3.9
- 5.2
- 7.1
- 10
zombie_tag:
  enabled: true
  min_drawdown_pct: 0.5
  max_drawdown_pct: 5
  max_score: 0.3
  require_zero_recovery_odds: true
  max_macd_lift: 0
  max_rsi_slope: 0
use_ml_spend_model: true
spend_adjustment_rules:
  min_volume: 20
  max_multiplier: 2  # 🔧 Lowered from 3 to reduce over-allocation
  tp1_shift_soft_cap: 2.5
  low_dd_pct_limit: 1
log_verbose: true
enforce_price_below_last_step: true
trailing_step_guard:
  enabled: true
  min_pct_gap_from_last_dca: 2.0
adaptive_step_spacing:
  enabled: false
require_macd_cross: false
macd_cross_lookback: 1
bottom_reversal_filter:
  enabled: false
  macd_lift_min: 1.0e-05
  rsi_slope_min: 0.45
  local_price_reversal_window: 3
  lookback_bars: 1
  rsi_floor: 35
bottom_reversal_trigger:
  enabled: true
  mode: soft
  require_btc_safe: false
  rsi_floor: 35
  macd_lift_min: 0.0003
  rsi_slope_min: 0.6
  candles_required: 5
