# /market7/config/paths_config.yaml

base_path: /home/signal/marketpilot
snapshots_path: /home/signal/marketpilot/data/snapshots
fork_history_path: /home/signal/marketpilot/output/fork_history
btc_logs_path: /home/signal/marketpilot/dashboard_backend/btc_logs
live_logs_path: /home/signal/marketpilot/live/logs
models_path: /home/signal/marketpilot/live/models
paper_cred_path: /home/signal/marketpilot/config/paper_cred.json
tv_history_path: /home/signal/marketpilot/output/tv_history
final_fork_rrr_trades: /home/signal/marketpilot/output/final_fork_rrr_trades.json
fork_tv_adjusted: /home/signal/marketpilot/output/fork_tv_adjusted.jsonl
dashboard_cache: /home/signal/marketpilot/dashboard_backend/cache
backtest_summary_path: /home/signal/marketpilot/backtest/data/summary
fork_candidates_path: /home/signal/marketpilot/output/fork_candidates.json
fork_backtest_candidates_path: /home/signal/marketpilot/output/fork_backtest_candidates.json
dca_tracking_log: /home/signal/marketpilot/dca/logs/dca_tracking/dca_fired.jsonl
dca_log_base: /home/signal/marketpilot/dca/logs/
ml_dataset_base: /home/signal/marketpilot/live/ml_dataset/
tv_screener_config_path: /home/signal/marketpilot/config/tv_screener_config.yaml
filtered_pairs_path: /home/signal/marketpilot/data/filtered_pairs.json
kline_snapshots: /home/signal/marketpilot/data/snapshots
fork_trade_candidates_path: /home/signal/marketpilot/output/fork_trade_candidates.json
final_forked_trades: /home/signal/marketpilot/output/final_forked_trades.json
binance_symbols: /home/signal/marketpilot/data/binance_symbols.json
dca_config: /home/signal/marketpilot/config/dca_config.yaml
fork_safu_config: /home/signal/marketpilot/config/fork_safu_config.yaml
enriched_path: /home/signal/marketpilot/ml/datasets/enriched
dca_tracking_path: /home/signal/marketpilot/dca/logs/dca_tracking/dca_fired.jsonl
recovery_snapshots_path: /home/signal/marketpilot/ml/datasets/recovery_snapshots
dca_spend_path: /home/signal/marketpilot/ml/datasets/dca_spend
