# /market7/config/paths_config.yaml

base_path: /workspace
snapshots_path: /workspace/data/snapshots
fork_history_path: /workspace/output/fork_history
btc_logs_path: /workspace/dashboard_backend/btc_logs
live_logs_path: /workspace/live/logs
models_path: /workspace/live/models
paper_cred_path: /workspace/config/paper_cred.json
tv_history_path: /workspace/output/tv_history
final_fork_rrr_trades: /workspace/output/final_fork_rrr_trades.json
fork_tv_adjusted: /workspace/output/fork_tv_adjusted.jsonl
dashboard_cache: /workspace/dashboard_backend/cache
backtest_summary_path: /workspace/backtest/data/summary
fork_candidates_path: /workspace/output/fork_candidates.json
fork_backtest_candidates_path: /workspace/output/fork_backtest_candidates.json
dca_tracking_log: /workspace/dca/logs/dca_tracking/dca_fired.jsonl
dca_log_base: /workspace/dca/logs/
ml_dataset_base: /workspace/live/ml_dataset/
tv_screener_config_path: /workspace/config/tv_screener_config.yaml
filtered_pairs_path: /workspace/data/filtered_pairs.json
kline_snapshots: /workspace/data/snapshots
fork_trade_candidates_path: /workspace/output/fork_trade_candidates.json
final_forked_trades: /workspace/output/final_forked_trades.json
binance_symbols: /workspace/data/binance_symbols.json
dca_config: /workspace/config/dca_config.yaml
fork_safu_config: /workspace/config/fork_safu_config.yaml
enriched_path: /workspace/ml/datasets/enriched
dca_tracking_path: /workspace/dca/logs/dca_tracking/dca_fired.jsonl
recovery_snapshots_path: /workspace/ml/datasets/recovery_snapshots
dca_spend_path: /workspace/ml/datasets/dca_spend
