min_score_long: 0.35
min_score_short: 0.35

weights_long:
  macd_histogram: 0.20
  macd_trend_cross: 0.15      # bull cross is good
  rsi_direction: 0.20         # rising from oversold
  stoch_rsi_cross: 0.15       # K>D under 80
  stoch_extreme_penalty: 0.10 # reward “not extreme”
  adx_rising: 0.10
  ema_trend_ok: 0.20          # price > EMA50
  mean_reversion_score: 0.10
  volume_penalty: -0.10
  stoch_rsi_slope: 0.10

weights_short:
  macd_histogram: 0.20
  macd_trend_cross: -0.15     # bear cross is good
  rsi_direction: 0.20         # falling from overbought
  stoch_rsi_cross: 0.15       # D>K above 20
  stoch_extreme_penalty: 0.10 # reward “not extreme”
  adx_rising: 0.10
  ema_trend_ok: 0.20          # price < EMA50
  mean_reversion_score: 0.10
  volume_penalty: -0.10
  stoch_rsi_slope: 0.10

options:
  use_volume_penalty: true
  use_btc_multiplier: true
