tv_screener:
  # Long side weights
  weights_long:
    strong_buy:   0.30
    buy:          0.20
    neutral:      0.00
    sell:        -0.20
    strong_sell: -0.30

  # Short side weights (inverted)
  weights_short:
    strong_sell:  0.30
    sell:         0.20
    neutral:      0.00
    buy:         -0.20
    strong_buy:  -0.30

  # Side-specific pass thresholds (after TV nudge)
  score_threshold_long:  0.45
  score_threshold_short: 0.35

  # Where we read raw TV tags (you can override via --tv-file)
  # Expected format: {"BTC":{"15m":"buy",...}, "ETH":{...}, ...}
  #default_tv_file: "/home/signal/market7/dashboard_backend/tv_screener_raw_dict.txt"
  default_tv_file: /home/signal/market7/output/tv_history/tv_screener_raw_dict.txt
