apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: market7-postgres-pvc
  namespace: market7
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
