apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: market7-logs-pvc
  namespace: market7
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
