apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: market7-models-pvc
  namespace: market7
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
