apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: market7-influxdb-pvc
  namespace: market7
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
