apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: market7-redis-pvc
  namespace: market7
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
